// Las 22 categorías iniciales y las palabras con las que se reconocen (generado desde la app nativa).
export const SEED = [
 {
  "key": "food",
  "name": "Comida y restaurantes",
  "icon": "utensils",
  "color": "#F97316",
  "kind": "expense",
  "keywords": [
   "almuerzo",
   "desayuno",
   "cena",
   "comida",
   "comidas",
   "corrientazo",
   "ejecutivo",
   "restaurante",
   "hamburguesa",
   "burger",
   "pizza",
   "perro caliente",
   "salchipapa",
   "empanada",
   "arepa",
   "pollo",
   "asado",
   "sushi",
   "taco",
   "tacos",
   "burrito",
   "cafe",
   "tinto",
   "capuchino",
   "cappuccino",
   "latte",
   "starbucks",
   "juan valdez",
   "tostao",
   "panaderia",
   "pan",
   "pandebono",
   "bunuelo",
   "postre",
   "helado",
   "onces",
   "merienda",
   "snack",
   "mecato",
   "domicilio",
   "rappi",
   "ifood",
   "didi food",
   "uber eats",
   "pedidosya",
   "mcdonalds",
   "kfc",
   "frisby",
   "crepes",
   "el corral",
   "subway",
   "dominos",
   "cerveza",
   "pola",
   "trago",
   "bar",
   "gaseosa",
   "jugo",
   "brunch",
   "lonchera",
   "almorzar",
   "cenar",
   "desayunar",
   "comer",
   "chocorramo",
   "galletas",
   "dulces",
   "fritanga",
   "bandeja paisa",
   "ajiaco",
   "tamal",
   "chicharron",
   "cafeteria",
   "comidas rapidas",
   "propina"
  ]
 },
 {
  "key": "groceries",
  "name": "Mercado",
  "icon": "cart",
  "color": "#22C55E",
  "kind": "expense",
  "keywords": [
   "mercado",
   "supermercado",
   "super",
   "exito",
   "carulla",
   "jumbo",
   "olimpica",
   "d1",
   "ara",
   "isimo",
   "justo y bueno",
   "makro",
   "pricesmart",
   "colsubsidio",
   "tienda",
   "tiendita",
   "fruver",
   "verduras",
   "frutas",
   "carne",
   "carniceria",
   "huevos",
   "leche",
   "arroz",
   "walmart",
   "soriana",
   "chedraui",
   "oxxo",
   "costco",
   "lider",
   "tottus",
   "plaza vea",
   "coto",
   "abarrotes",
   "viveres",
   "despensa",
   "surtimax",
   "mercadito",
   "minimercado",
   "mercar",
   "plaza de mercado",
   "granos",
   "aceite",
   "azucar",
   "cafe molido"
  ]
 },
 {
  "key": "transport",
  "name": "Transporte",
  "icon": "car",
  "color": "#3B82F6",
  "kind": "expense",
  "keywords": [
   "uber",
   "didi",
   "taxi",
   "cabify",
   "indriver",
   "indrive",
   "picap",
   "bus",
   "buseta",
   "colectivo",
   "transmilenio",
   "sitp",
   "mio",
   "metro",
   "metrocable",
   "metroplus",
   "tranvia",
   "pasaje",
   "pasajes",
   "tullave",
   "civica",
   "parqueadero",
   "parking",
   "estacionamiento",
   "peaje",
   "lavado carro",
   "lavado moto",
   "moto",
   "patineta",
   "scooter",
   "tren",
   "subte",
   "micro",
   "transporte",
   "mototaxi",
   "bolt",
   "carro",
   "mecanico",
   "taller",
   "llantas",
   "aceite del carro",
   "revision del carro",
   "recarga tarjeta"
  ]
 },
 {
  "key": "fuel",
  "name": "Gasolina",
  "icon": "fuel",
  "color": "#0EA5E9",
  "kind": "expense",
  "keywords": [
   "gasolina",
   "tanqueo",
   "tanquear",
   "tanquee",
   "combustible",
   "diesel",
   "acpm",
   "gas vehicular",
   "gnv",
   "terpel",
   "texaco",
   "primax",
   "esso",
   "mobil",
   "biomax",
   "zeuss",
   "petrobras",
   "shell",
   "pemex",
   "ypf",
   "bomba",
   "estacion de servicio"
  ]
 },
 {
  "key": "home",
  "name": "Hogar y arriendo",
  "icon": "home",
  "color": "#A16207",
  "kind": "expense",
  "keywords": [
   "arriendo",
   "alquiler",
   "renta",
   "administracion",
   "hipoteca",
   "cuota casa",
   "muebles",
   "mueble",
   "decoracion",
   "ferreteria",
   "homecenter",
   "easy",
   "reparacion",
   "plomero",
   "electricista",
   "aseo",
   "detergente",
   "limpieza",
   "empleada",
   "empleada domestica",
   "lavanderia",
   "cortinas",
   "colchon",
   "electrodomestico",
   "nevera",
   "lavadora",
   "hogar",
   "casa",
   "apartamento",
   "arreglo"
  ]
 },
 {
  "key": "utilities",
  "name": "Servicios públicos",
  "icon": "bolt",
  "color": "#EAB308",
  "kind": "expense",
  "keywords": [
   "luz",
   "energia",
   "agua",
   "acueducto",
   "gas",
   "gas natural",
   "vanti",
   "epm",
   "enel",
   "codensa",
   "servicios",
   "servicios publicos",
   "recibo de luz",
   "recibo del agua",
   "recibo del gas",
   "alcantarillado",
   "basuras",
   "afinia",
   "air e",
   "electricaribe",
   "triple a",
   "recibo",
   "recibos"
  ]
 },
 {
  "key": "telecom",
  "name": "Internet y celular",
  "icon": "wifi",
  "color": "#6366F1",
  "kind": "expense",
  "keywords": [
   "internet",
   "wifi",
   "celular",
   "plan celular",
   "plan de datos",
   "datos",
   "recarga",
   "recarga celular",
   "minutos",
   "claro",
   "movistar",
   "tigo",
   "wom",
   "etb",
   "une",
   "telcel",
   "entel",
   "starlink",
   "fibra",
   "telefono",
   "television",
   "directv",
   "cable"
  ]
 },
 {
  "key": "health",
  "name": "Salud",
  "icon": "pulse",
  "color": "#EF4444",
  "kind": "expense",
  "keywords": [
   "medico",
   "medica",
   "doctor",
   "cita medica",
   "eps",
   "medicina",
   "medicamento",
   "medicamentos",
   "drogueria",
   "farmacia",
   "pastillas",
   "examen",
   "examenes",
   "laboratorio",
   "odontologo",
   "dentista",
   "ortodoncia",
   "optica",
   "gafas",
   "lentes",
   "terapia",
   "psicologo",
   "hospital",
   "clinica",
   "urgencias",
   "copago",
   "cruz verde",
   "farmatodo",
   "la rebaja",
   "colsanitas",
   "prepagada",
   "seguro medico",
   "vitaminas",
   "gym",
   "gimnasio",
   "smart fit",
   "bodytech",
   "crossfit",
   "yoga",
   "salud",
   "vacuna",
   "consulta"
  ]
 },
 {
  "key": "education",
  "name": "Educación",
  "icon": "cap",
  "color": "#8B5CF6",
  "kind": "expense",
  "keywords": [
   "colegio",
   "universidad",
   "matricula",
   "semestre",
   "pension del colegio",
   "curso",
   "cursos",
   "clases",
   "clase",
   "libro",
   "libros",
   "utiles",
   "cuadernos",
   "fotocopias",
   "copias",
   "impresiones",
   "platzi",
   "udemy",
   "coursera",
   "ingles",
   "diplomado",
   "maestria",
   "icfes",
   "educacion",
   "jardin",
   "guarderia",
   "uniforme",
   "tutoria",
   "moodle"
  ]
 },
 {
  "key": "fun",
  "name": "Entretenimiento",
  "icon": "gamepad",
  "color": "#EC4899",
  "kind": "expense",
  "keywords": [
   "cine",
   "cinecolombia",
   "cinemark",
   "procinal",
   "cinepolis",
   "pelicula",
   "concierto",
   "boletas",
   "boleta",
   "entradas",
   "teatro",
   "fiesta",
   "rumba",
   "discoteca",
   "bolos",
   "parque",
   "videojuego",
   "videojuegos",
   "playstation",
   "xbox",
   "nintendo",
   "steam",
   "futbol",
   "partido",
   "estadio",
   "museo",
   "salida",
   "paseo",
   "karaoke",
   "billar",
   "tejo",
   "apuesta",
   "apuestas",
   "loteria",
   "chance",
   "betplay",
   "wplay",
   "casino",
   "entretenimiento",
   "juego",
   "juegos",
   "plan con amigos"
  ]
 },
 {
  "key": "subscriptions",
  "name": "Suscripciones",
  "icon": "screen",
  "color": "#D946EF",
  "kind": "expense",
  "keywords": [
   "netflix",
   "spotify",
   "disney",
   "hbo",
   "prime video",
   "amazon prime",
   "youtube premium",
   "youtube",
   "apple music",
   "icloud",
   "apple tv",
   "apple one",
   "paramount",
   "crunchyroll",
   "deezer",
   "chatgpt",
   "claude",
   "canva",
   "adobe",
   "office",
   "microsoft 365",
   "google one",
   "suscripcion",
   "suscripciones",
   "membresia",
   "game pass",
   "playstation plus",
   "duolingo",
   "tinder",
   "bumble",
   "mubi",
   "vix",
   "star plus"
  ]
 },
 {
  "key": "clothing",
  "name": "Ropa y accesorios",
  "icon": "shirt",
  "color": "#14B8A6",
  "kind": "expense",
  "keywords": [
   "ropa",
   "camisa",
   "camiseta",
   "pantalon",
   "jean",
   "jeans",
   "zapatos",
   "tenis",
   "zapatillas",
   "vestido",
   "falda",
   "chaqueta",
   "buzo",
   "medias",
   "ropa interior",
   "zara",
   "bershka",
   "pull and bear",
   "stradivarius",
   "koaj",
   "arturo calle",
   "studio f",
   "adidas",
   "nike",
   "puma",
   "bolso",
   "cartera",
   "reloj",
   "accesorios",
   "gorra",
   "pijama",
   "brasier",
   "boxer",
   "sandalias",
   "botas"
  ]
 },
 {
  "key": "shopping",
  "name": "Compras",
  "icon": "bag",
  "color": "#F43F5E",
  "kind": "expense",
  "keywords": [
   "compras",
   "amazon",
   "mercado libre",
   "mercadolibre",
   "temu",
   "shein",
   "aliexpress",
   "falabella",
   "ktronix",
   "alkosto",
   "tecnologia",
   "audifonos",
   "computador",
   "portatil",
   "tablet",
   "electronica",
   "juguete",
   "juguetes",
   "papeleria",
   "miniso",
   "dollarcity",
   "ikea",
   "target",
   "liverpool",
   "coppel",
   "ripley",
   "cargador",
   "cable usb",
   "iphone",
   "celular nuevo",
   "funda",
   "forro"
  ]
 },
 {
  "key": "care",
  "name": "Cuidado personal",
  "icon": "sparkle",
  "color": "#FB7185",
  "kind": "expense",
  "keywords": [
   "peluqueria",
   "barberia",
   "corte de pelo",
   "corte",
   "motilada",
   "manicure",
   "pedicure",
   "unas",
   "spa",
   "masaje",
   "maquillaje",
   "cosmeticos",
   "crema",
   "shampoo",
   "perfume",
   "desodorante",
   "depilacion",
   "cejas",
   "pestanas",
   "salon de belleza",
   "tratamiento",
   "skincare",
   "afeitadora",
   "jabon",
   "cuidado personal",
   "cepillo",
   "crema dental"
  ]
 },
 {
  "key": "pets",
  "name": "Mascotas",
  "icon": "paw",
  "color": "#B45309",
  "kind": "expense",
  "keywords": [
   "mascota",
   "mascotas",
   "perro",
   "perrito",
   "gato",
   "gatito",
   "concentrado",
   "comida del perro",
   "comida para perro",
   "comida del gato",
   "comida para gato",
   "veterinario",
   "veterinaria",
   "vacuna del perro",
   "peluqueria canina",
   "arena para gato",
   "purina",
   "dog chow",
   "cat chow",
   "pet",
   "juguete del perro"
  ]
 },
 {
  "key": "travel",
  "name": "Viajes",
  "icon": "plane",
  "color": "#06B6D4",
  "kind": "expense",
  "keywords": [
   "viaje",
   "vuelo",
   "tiquete",
   "tiquetes",
   "avion",
   "aerolinea",
   "avianca",
   "latam",
   "wingo",
   "jetsmart",
   "volaris",
   "aeromexico",
   "hotel",
   "hostal",
   "airbnb",
   "booking",
   "hospedaje",
   "alojamiento",
   "vacaciones",
   "maleta",
   "equipaje",
   "tour",
   "excursion",
   "crucero",
   "visa",
   "pasaporte",
   "terminal",
   "intermunicipal",
   "finca",
   "playa"
  ]
 },
 {
  "key": "gifts",
  "name": "Regalos y donaciones",
  "icon": "gift",
  "color": "#E11D48",
  "kind": "expense",
  "keywords": [
   "regalo",
   "regalos",
   "obsequio",
   "cumpleanos",
   "detalle",
   "flores",
   "donacion",
   "diezmo",
   "ofrenda",
   "limosna",
   "aporte",
   "navidad",
   "amigo secreto",
   "vaca",
   "ancheta"
  ]
 },
 {
  "key": "debt",
  "name": "Deudas e impuestos",
  "icon": "card",
  "color": "#64748B",
  "kind": "expense",
  "keywords": [
   "tarjeta de credito",
   "tarjeta",
   "credito",
   "prestamo",
   "cuota",
   "cuotas",
   "deuda",
   "abono",
   "intereses de la tarjeta",
   "banco",
   "cuota de manejo",
   "comision bancaria",
   "4x1000",
   "gmf",
   "leasing",
   "credito hipotecario",
   "addi",
   "sistecredito",
   "multa",
   "comparendo",
   "impuesto",
   "impuestos",
   "predial",
   "dian",
   "soat",
   "tecnomecanica",
   "seguro",
   "seguros",
   "poliza",
   "icetex",
   "fotomulta"
  ]
 },
 {
  "key": "other",
  "name": "Otros gastos",
  "icon": "dots",
  "color": "#94A3B8",
  "kind": "expense",
  "keywords": [
   "otro",
   "otros",
   "varios",
   "gasto"
  ]
 },
 {
  "key": "salary",
  "name": "Salario",
  "icon": "wallet",
  "color": "#16A34A",
  "kind": "income",
  "keywords": [
   "salario",
   "sueldo",
   "nomina",
   "quincena",
   "prima",
   "pago de nomina",
   "me pagaron",
   "cesantias",
   "bono",
   "bonificacion",
   "pago mensual",
   "mesada",
   "pension de vejez"
  ]
 },
 {
  "key": "business",
  "name": "Negocio y ventas",
  "icon": "briefcase",
  "color": "#059669",
  "kind": "income",
  "keywords": [
   "venta",
   "ventas",
   "vendi",
   "cliente",
   "factura",
   "honorarios",
   "freelance",
   "proyecto",
   "comision",
   "comisiones",
   "negocio",
   "emprendimiento",
   "ganancia",
   "ganancias",
   "hotmart",
   "shopify",
   "dropi",
   "utilidades",
   "pedido",
   "trabajo extra"
  ]
 },
 {
  "key": "otherIncome",
  "name": "Otros ingresos",
  "icon": "coinIn",
  "color": "#10B981",
  "kind": "income",
  "keywords": [
   "reembolso",
   "devolucion",
   "me devolvieron",
   "me regalaron",
   "rendimientos",
   "dividendos",
   "intereses ganados",
   "arriendo recibido",
   "transferencia recibida",
   "premio",
   "cashback",
   "ingreso",
   "ingresos"
  ]
 }
];

export const FALLBACK = { expense: 'other', income: 'otherIncome' };
